In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_headmotion=pd.read_csv('motion_predictions.csv')
df_noheadmotion=pd.read_csv('nomotion_predictions.csv')

In [3]:
df_participantdata = pd.read_csv('participants.tsv', sep='\t')

In [4]:
df_participantdata.head()

  participant_id  age   sex
0      sub-NC150   42  Male
1      sub-NC183   28  Male
2      sub-NC188   52  Male
3      sub-NC189   56  Male
4      sub-NC216   27  Male

In [5]:
df_participantdata = df_participantdata.drop(
    df_participantdata[
        df_participantdata['participant_id'].isin(['sub-NC225', 'sub-NC251'])
    ].index
)

In [6]:
df_participantdata['real_age']=df_participantdata['age']
df_participantdata['real_sex']=df_participantdata['sex']
df_participantdata=df_participantdata.drop('sex', axis=1)
df_participantdata=df_participantdata.drop('age', axis=1)

In [7]:
df_participantdata.head()

  participant_id  real_age real_sex
0      sub-NC150        42     Male
1      sub-NC183        28     Male
2      sub-NC188        52     Male
3      sub-NC189        56     Male
4      sub-NC216        27     Male

In [8]:
df_noheadmotion['participant_id']='sub-'+df_noheadmotion['subject']
df_headmotion['participant_id']='sub-'+df_headmotion['subject']

In [9]:
df_noheadmotion=df_noheadmotion.drop(['source', 'run', 'session', 'subject'],axis=1)
df_headmotion=df_headmotion.drop(['source', 'run', 'session', 'subject'],axis=1)

In [10]:
df_noheadmotion = df_noheadmotion.rename(
    columns=lambda col: col if col == 'participant_id' else 'nomotion_' + col
)

df_headmotion = df_headmotion.rename(
    columns=lambda col: col if col == 'participant_id' else 'motion_' + col
)

In [11]:
df= pd.merge(df_participantdata, df_noheadmotion, on='participant_id')
df= pd.merge(df, df_headmotion, on='participant_id')

In [12]:
df.head()

,participant_id,real_age,real_sex,nomotion_age,nomotion_sex,nomotion_handedness,nomotion_bmi,nomotion_fluid_intelligence,nomotion_neuroticism,motion_age,motion_sex,motion_handedness,motion_bmi,motion_fluid_intelligence,motion_neuroticism
0,sub-NC150,42,Male,35.724240,0.999888,0.002038,26.205930,0.423997,-0.006433,33.912937,0.999132,0.002312,25.666060,0.220162,0.016456
1,sub-NC183,28,Male,24.071867,0.993208,0.006977,21.673967,-0.016893,-0.101148,27.218252,0.999845,0.008577,22.249702,-0.087082,-0.053923
2,sub-NC188,52,Male,56.300518,0.999722,0.003651,24.680128,0.193321,-0.080030,52.371117,0.999355,0.007383,23.950453,0.037053,-0.131808
3,sub-NC189,56,Male,59.404533,0.978784,0.004347,24.910831,0.224922,-0.043789,58.310130,0.961742,0.003383,27.841696,-0.118790,0.052526
4,sub-NC216,27,Male,22.259346,0.135934,0.004544,25.788870,-0.000131,0.128404,28.275888,0.919534,0.004507,27.214000,-0.260030,0.153229

In [13]:
df.to_csv('cleaned_data.csv', index=False)